### ISSUE TITLE
Notify when category changes

### ISSUE THREAD

**Issue by AlexWayfer** [Satont/twitch-notifier#1]
Hello!

Thank you for Telegram bot, it's comfortable enough.

But I don't want to see some categories on channels I follow. Like, I may not to like Game A and want to watch Game B. And streamer can start a stream with Game A, and I don't open it, and then switch to Game B, and I want to be notified about this.

Thank you.

**Comment by Satont** [comment]
Hi, @AlexWayfer.
Thank you for using the bot and for first issue.

Can you clarify one moment, do you wan't receive notification if stream was started with `Game A` and you ignored it?

Also how as in your vision you should add some `Game` in ignore list?

**Comment by AlexWayfer** [comment]
> Can you clarify one moment, do you wan't receive notification if stream was started with Game A and you ignored it?

I don't think that bot can check if I ignored stream or not, so notifications about any change (of followed channels) would be good.

> Also how as in your vision you should add some Game in ignore list?

This issue not about ignore list. About more notifications. Now we have notifications about event "go live", and I want notifications about "category changed".

Then, in another issue, we can implement black list of categories. I didn't mind about this.

**Comment by AlexWayfer** [comment]
This issue has been funded: https://www.bountysource.com/issues/84211988-notify-when-category-changes
