### ISSUE TITLE
Set VK group online status

### ISSUE THREAD

**Issue by Satont** [Satont/twitch-notifier#11]
Use some interval for set VK group messages as online.

https://vk.com/dev/groups.enableOnline

**Comment by AlexWayfer** [comment]
> Satont closed this 18 hours ago

Why?

**Comment by Satont** [comment]
@AlexWayfer currently i don't know how to determine group id from bot token.

So, when i'll release way, i'll reopen issue.

**Comment by AlexWayfer** [comment]
> @AlexWayfer currently i don't know how to determine group id from bot token.
> 
> So, when i'll release way, i'll reopen issue.

I guess, this is the way: https://vk.com/dev/bots_docs?f=1.%20Communities

Also I see `group_id` in something about callbacks.

Is not it helpful?

Also maybe group id should be set like config, alongside with token.

**Comment by Satont** [comment]
> Also I see group_id in something about callbacks.

Right. And there is no way.

> Also maybe group id should be set like config, alongside with token.

It's good suggestion.

I think i can add env variable for that, and check if it's not checked -> then wait for some group event, and retrieve group id from event.

**Comment by Satont** [comment]
Won't add because #73
