### ISSUE TITLE
Use "Go live notification" for notification text

### ISSUE THREAD

**Issue by AlexWayfer** [Satont/twitch-notifier#12]
Hello!

There is editable notification text:

![image](https://user-images.githubusercontent.com/6510020/74092481-7cc50e80-4ad5-11ea-8956-9114ed79cd6d.png)

Can we use it for notification text instead of `%{channel} online`?

**Comment by Satont** [comment]
Hi.

Currently twitch doesn't provide api for get stream notification message.

**Comment by AlexWayfer** [comment]
That's said.
