### ISSUE TITLE
Use regexp intead of hardcoded space character

### ISSUE THREAD

**Issue by Satont** [Satont/twitch-notifier#16]
Referenced to https://github.com/Satont/twitch-notifier/issues/14, https://github.com/Satont/twitch-notifier/commit/60a1b2a2dcfdbc0b9227b1e9e078e95ce18c5961

I should use some regexp, instead of 
```js 
status !== ' '
```

**Comment by AlexWayfer** [comment]
I suggest something like `/^\s*$/`.

**Comment by Satont** [comment]
> I suggest something like `/^\s*$/`.

Thank you. I'm not very good in writing regular expressions. :)
