### ISSUE TITLE
Use buttons markup for commands

### ISSUE THREAD

**Issue by AlexWayfer** [Satont/twitch-notifier#3]
It may be more handful than commands via slashes.

**Comment by AlexWayfer** [comment]
It seems implemented, but not sure about your opinion.

**Comment by Satont** [comment]
> It seems implemented, but not sure about your opinion.

If that issue about /follow, /follows, /live, e.t.c, then it't still not implemented.

Current markup is just settings menu, not commands.

**Comment by AlexWayfer** [comment]
Hm. It's not easy to imagine `/follow` with buttons markup, but OK, right now this function seems ugly, yes:

```
> /follow
< Username can only contain "a-z", "0-9" and "_" symbols.
```

**Comment by Satont** [comment]
Yep, thats why your issue not implemented currently.

First of i need write scenes for `/follow`, `/unfollow` commands, for promt the user.

**Comment by Satont** [comment]
I do not feel like i need duplicate telegram commands list like in that way:

![](https://i.imgur.com/d6o0fOZ.png)

So, telegram commands list seems pretty good and native:

![](https://i.imgur.com/fYdvMpf.png)

So, i just added "scenes" to commands, where it requires additional user input, like `follow` command.
