### ISSUE TITLE
Add a command to import friends for notifications

### ISSUE THREAD

**Issue by AlexWayfer** [Satont/twitch-notifier#32]
Hello.

It'd be handful to have a command, like `/import_from_friends`, to enable notifications for each friend (at single command usage, not regular refresh).

**Comment by Satont** [comment]
Hi.

Sadly, but twitch do not provide of friends api.

**Comment by AlexWayfer** [comment]
> Hi.
> 
> Sadly, but twitch do not provide of friends api.

Oh, it's actually sad…

I've found info that Friends API is in beta, and such non-official documentation: https://github.com/justintv/Twitch-API/issues/545#issuecomment-217583786

Can you please try it or do you now want to?

**Comment by Satont** [comment]
Do you understand it will requires user authentication anyway?

It's kind of complicated for such project. 

Also twitch even haven't such scopes described in issue.

**Comment by Satont** [comment]
Also as i see twitch disabled such endpoints.

They migrated to gpl instead.

**Comment by AlexWayfer** [comment]
> Do you understand it will requires user authentication anyway?

OK, know I understand. Thank you.
