### ISSUE TITLE
Add an option to get notifications about stream end

### ISSUE THREAD

**Issue by AlexWayfer** [Satont/twitch-notifier#33]
Sometimes I read a notification that some channel started stream too late, and I'd like too see a similar notification that this channel stopped stream before opening a channel link.

**Comment by Satont** [comment]
Do you wan't that feature like game notification change? I mean global setting or per channel?

**Comment by AlexWayfer** [comment]
> Do you wan't that feature like game notification change? I mean global setting or per channel?

I'm OK with global one, see no reason to complicate interface with per-channel settings.

If I'm ready to get all notifications about somebody's online — I'm ready to get offline notifications too.

**Comment by Satont** [comment]
> > Do you wan't that feature like game notification change? I mean global setting or per channel?
> 
> I'm OK with global one, see no reason to complicate interface with per-channel settings.
> 
> If I'm ready to get all notifications about somebody's online — I'm ready to get offline notifications too.

Ok, thank you for your reply. I think that setting can be added quickly.
