### ISSUE TITLE
Real-time list of live channels

### ISSUE THREAD

**Issue by AlexWayfer** [Satont/twitch-notifier#44]
Hello.

I know about `/live` command which prints list of live followed channels.

But it can be helpful to have real-time renewing list instead of re-sending this command manually.

Suggestion: use pinning messages (in Telegram, not sure about other platforms).

Telegram has pins even in direct messages from recent times, and user can pin a message for a bot via checkbox:

![image](https://user-images.githubusercontent.com/6510020/101620524-b46a5300-3a25-11eb-8432-2ae6b3a9ff3f.png)

So, I think, bot can receive this event and start edit pinned message at online/offline events if pinned message is a response to `/live` command.

**Comment by AlexWayfer** [comment]
I'm pretty sure it's not completed, but I'm also pretty sure that bots have same limitations as people in chats with others (saved messages is an exception): editing only in first 2 hours. So, this issue propably is pointless.

**Comment by Satont** [comment]
True, wont do that.

вт, 28 мар. 2023 г. в 22:26, Alexander Popov ***@***.***>:
