### ISSUE TITLE
Title change notifications

### ISSUE THREAD

**Issue by AlexWayfer** [Satont/twitch-notifier#45]
Similar to #1, but for titles.

I'm pretty sure that separate setting is not necessary, there can be a single for category and title.

**Comment by Satont** [comment]
WHy you want that? For what?

**Comment by AlexWayfer** [comment]
If it's hard — OK, you can set "won't be implemented" or something like that. Or wait for a contribution.

But… there can be situations when a single streamer streams single game (category), but firstly with good mood like "happy to see you here" title, but then the same category, still online, with bad mood like "fuck off". So, I'd interested in changes like these. It's not too often case I think, but it can be, and when it'll — I'd like to know about it.

**Comment by Satont** [comment]
> If it's hard — OK, you can set "won't be implemented" or something like that. 

Nope, i just see no point.

> But… there can be situations when a single streamer streams single game (category), but firstly with good mood like "happy to see you here" title, but then the same category, still online, with bad mood like "fuck off". So, I'd interested in changes like these. It's not too often case I think, but it can be, and when it'll — I'd like to know about it.

Still very rare case. I rarely see people express such a mood in stream title's.

It's not that hard.

> I'm pretty sure that separate setting is not necessary, there can be a single for category and title.

Well, i'm as user enver wants recieve such notifications, so, if i'll do that, then it will be separeted from game change notifications.

**Comment by AlexWayfer** [comment]
> Still very rare case. I rarely see people express such a mood in stream title's.

OK, another (rare too, I think) case: "Science" category and different projects in the title during single stream.



> Well, as user, i want never recieve such notifications, so, if i'll do that, then it will be separeted from game change notifications.

Sadly, OK.

**Comment by Satont** [comment]
> > [Satont](https://github.com/Satont) closed this as [completed](https://github.com/Satont/twitch-notifier/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [2 days ago](https://github.com/Satont/twitch-notifier/issues/45#event-8868355773)
> 
> Is it completed? I really need for it, especially with new compact notifications.

Not completed. Reoped if it still the case.

**Comment by AlexWayfer** [comment]
> > > [Satont](https://github.com/Satont) closed this as [completed](https://github.com/Satont/twitch-notifier/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [2 days ago](https://github.com/Satont/twitch-notifier/issues/45#event-8868355773)
> > 
> > 
> > Is it completed? I really need for it, especially with new compact notifications.
> 
> Not completed. Reopen if it still the case.

Dude, I have no "Reopen" button.

![image](https://user-images.githubusercontent.com/6510020/228898913-a9b2bff5-d846-475a-a91d-0193aac038ef.png)

Yes, it's still the case.
