### ISSUE TITLE
Add `/cancel` command

### ISSUE THREAD

**Issue by LWJerri** [Satont/twitch-notifier#49]
Sometimes peoples can write missed commands and can't back because the command wanna get an argument. Can you add `/cancel` command for the undo user action?

**Comment by AlexWayfer** [comment]
If you send another command (starting with `/`) — what happens?

**Comment by Satont** [comment]
@AlexWayfer currently it will wait user input in any way, until TTL of stage not ends.

I'm agreed, i need to implement `/cancel` command.
