### ISSUE TITLE
Команды ВКонтакте 

### ISSUE THREAD

**Issue by dmsergeevich63** [Satont/twitch-notifier#50]
Здравствуйте, у меня уже несколько месяцев не работают и даже не читаются команды в группе [vk](https://vk.com/twitchnotify)
![image](https://user-images.githubusercontent.com/47436708/104095149-b33f7680-52ae-11eb-8c9e-42c8ffd5c9c7.png)

**Comment by Satont** [comment]
Здравствуйте. Команды теперь пишутся через `/`

Посмотреть актуальный список команд можно написав `/start`

**Comment by dmsergeevich63** [comment]
Спасибо, только поправьте [пост ](https://vk.com/twitchnotify?w=wall-187752469_25) в гриппе, вы написали "/команды".

**Comment by Satont** [comment]
Значит проблема решена? Здорово, закрываю issue.
