### ISSUE TITLE
Не работает подписка Telegram

### ISSUE THREAD

**Issue by dmsergeevich63** [Satont/twitch-notifier#58]
Здравствуйте, команда /follow не добавляется стримеров по нику, бот ожидает от меня ник, но он игнорирует сообщение с ником! Проверка на наличие подписки работает. Также команда /live ничего не выводит, но она не особо важна для меня.
![image](https://user-images.githubusercontent.com/47436708/114737775-6610ec00-9d58-11eb-86a6-a8b6a9e8bbc1.png)![image](https://user-images.githubusercontent.com/47436708/114736146-e6cee880-9d56-11eb-8646-8002d858a7ee.png)![image](https://user-images.githubusercontent.com/47436708/114736791-770d2d80-9d57-11eb-83e3-9fad781382f9.png)

**Comment by Satont** [comment]
Здравствуйте. Можно узнать ваш telegram id?

**Comment by dmsergeevich63** [comment]
Id: 21123648

**Comment by AlexWayfer** [comment]
Подтверждаю, отвечает только тогда, когда уже подписан. Ник значения не имеет:

![image](https://user-images.githubusercontent.com/6510020/114742803-c30aa300-9d54-11eb-81ea-a94f6d21525c.png)

**Comment by Satont** [comment]
Странно, но это из-за записей в БД, где channelId = null.

Хотя это не должно влиять на `/follow`, но всё же как-то влияло.

Вычистил такие записи из БД, добавил миграцию на явный not nullable https://github.com/Satont/twitch-notifier/commit/dd451b9ea6a61227b4ec5ea06721e952ef86c3f3

Проблема должна исчезнуть, но точно пока не знаю. Если всё ещё актуально — отпишитесь сюда.

**Comment by dmsergeevich63** [comment]
Команды /follow и /live заработали, спасибо!
