### ISSUE TITLE
Add discord service

### ISSUE THREAD

**Issue by Satont** [Satont/twitch-notifier#74]

**Comment by AlexWayfer** [comment]
> [Satont](https://github.com/Satont) closed this as [completed](https://github.com/Satont/twitch-notifier/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [1 hour ago](https://github.com/Satont/twitch-notifier/issues/74#event-8868356142)

Is it actually completed?

**Comment by Satont** [comment]
Nope, reopen issue if it still the case.

вт, 28 мар. 2023 г. в 22:22, Alexander Popov ***@***.***>:

**Comment by AlexWayfer** [comment]
FYI, I have no "Reopen" button. But no, for me it's not a case yet.
