### ISSUE TITLE
Restore the site or update links to it

### ISSUE THREAD

**Issue by AlexWayfer** [Satont/twitch-notifier#90]
https://livenotifier.tk/

![image](https://user-images.githubusercontent.com/6510020/228345447-7494df8a-1756-44b9-ae44-79938ca0966b.png)

![image](https://user-images.githubusercontent.com/6510020/228345483-c7b841d4-1f35-4cdf-b514-146e89306f8b.png)

![image](https://user-images.githubusercontent.com/6510020/228345542-76f3402c-3cef-4885-a489-86a38514e927.png)

**Comment by Satont** [comment]
It's undeployed currently.

вт, 28 мар. 2023 г. в 22:24, Alexander Popov ***@***.***>:

**Comment by Satont** [comment]
Link updated. There is no site, currently. Maybe in future.

**Comment by AlexWayfer** [comment]
> Link updated.

Not in the bot description.
