### ISSUE TITLE
Do not send message twice when title and category changed

### ISSUE THREAD

**Issue by Satont** [Satont/twitch-notifier#95]
When title and category both changed, then bot will send 2 messages. We should send message only once, where will be information about new title and category,

**Comment by AlexWayfer** [comment]
Also it'll resolve the weird screenshot duplication in two messages in a row:

![image](https://user-images.githubusercontent.com/6510020/232565522-62ec9086-15a0-42fd-ad2a-402b7ac1c0c1.png)

It could be resolved via image disabling for title change, but the solutuion from this issue is better.
