### ISSUE TITLE
Delay for category/title change

### ISSUE THREAD

**Issue by AlexWayfer** [Satont/twitch-notifier#98]
Can be related to #95.

But the more related details, also relevant before "title change" feature introduction:

When a category has been changed — bot sends notifications immediately. It's good from one side, but the other side — screenshots always have delays.

So, I usulally see such picture:

![image](https://user-images.githubusercontent.com/6510020/232565975-aa077114-8de0-4ea0-8965-8e0a98d2579d.png)

![image](https://user-images.githubusercontent.com/6510020/232565999-ad1609e6-66dc-42f9-b5bf-adef7917b225.png)

![image](https://user-images.githubusercontent.com/6510020/232566029-769b3b83-2e45-48b6-a469-e85975ca61f9.png)

![image](https://user-images.githubusercontent.com/6510020/232566108-f8589f8c-9792-41e3-b9e5-d3e6e8506da3.png)

![image](https://user-images.githubusercontent.com/6510020/232566234-c93e1790-ffbb-4525-a929-c09ed8835c0a.png)

![image](https://user-images.githubusercontent.com/6510020/232566270-aa3eecf4-56d5-42a1-9bd8-36b876d5c75f.png)

Another advantage that we can achive with this issue: don't notify about fault or testing category changes in short periods.

**Comment by danilluk1** [comment]
Bot is not sending notification immediately, it just calls Twitch API every 1 minute. And you are right - twitch thumbnails have 5 minutes delay, how it is said in docs, so this is why we have wrong images.

I think we can up delay time to maybe 6 minutes, to fix this problem. Or we will add new settings, where users can choose what they want more speed or accuracy. Also it will decrease counts of miss notifications when categories changes very fast.

**Comment by AlexWayfer** [comment]
> I think we can up delay time to maybe 6 minutes, to fix this problem. Or we will add new settings, where users can choose what they want more speed or accuracy.

Both options seem legit to me.
